// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXGqnyQ6fdY-ZAEaQNueXLqlCUVY0ZnjM',
    appId: '1:124644858042:web:1cdc64af7cd4e8853fca83',
    messagingSenderId: '124644858042',
    projectId: 'pawguardai',
    authDomain: 'pawguardai.firebaseapp.com',
    storageBucket: 'pawguardai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgvWHZV3JD-OgpUbKBN5NkGb79F6ImNkE',
    appId: '1:124644858042:android:6545550b941ff3553fca83',
    messagingSenderId: '124644858042',
    projectId: 'pawguardai',
    storageBucket: 'pawguardai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl5ZrwU3O5P7sjwOckCTx0TiEXKnZUF9Q',
    appId: '1:337125078504:ios:880890f3cafaadd5e2205d',
    messagingSenderId: '337125078504',
    projectId: 'flutter-ai-playground-ef174',
    storageBucket: 'flutter-ai-playground-ef174.firebasestorage.app',
    iosBundleId: 'com.example.pawguardAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl5ZrwU3O5P7sjwOckCTx0TiEXKnZUF9Q',
    appId: '1:337125078504:ios:880890f3cafaadd5e2205d',
    messagingSenderId: '337125078504',
    projectId: 'flutter-ai-playground-ef174',
    storageBucket: 'flutter-ai-playground-ef174.firebasestorage.app',
    iosBundleId: 'com.example.pawguardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXGqnyQ6fdY-ZAEaQNueXLqlCUVY0ZnjM',
    appId: '1:124644858042:web:c126a98c137cd44c3fca83',
    messagingSenderId: '124644858042',
    projectId: 'pawguardai',
    authDomain: 'pawguardai.firebaseapp.com',
    storageBucket: 'pawguardai.firebasestorage.app',
  );

}